# By Oleksiy Grechnyev

import sys
import argparse
import pathlib
import pickle
import easydict

import numpy as np

from src.cv_module.people.people_range_estimation_v2 import PeopleRangeEstimator


########################################################################################################################
def print_it(a, name: str = ''):
    # m = a.float().mean() if isinstance(a, torch.Tensor) else a.mean()
    m = a.mean()
    print(name, a.shape, a.dtype, a.min(), m, a.max())


########################################################################################################################
# Like easydict, with some extras
class FakePerson:
    def __init__(self, d: dict):
        self._d = d

    def set_measurement(self, meas):
        self._d['meas'] = meas

    def __str__(self):
        return str(self._d)

    def __setattr__(self, key, value):
        if key in ['_d']:
            super().__setattr__(key, value)
        else:
            self._d[key] = value

    def __getattr__(self, item):
        return self._d[item]


########################################################################################################################
def main():
    parser = argparse.ArgumentParser(
        description='Run a .pkl file generated by main_oleksiy_recorder via sloth',
    )
    parser.add_argument('input_file', help='PKL file generated by main_oleksiy_recorder', type=pathlib.Path)
    args = parser.parse_args()

    # Read data
    assert args.input_file.exists()
    with open(args.input_file, 'rb') as f:
        data = pickle.load(f)
    people_range_estimator = PeopleRangeEstimator(data['focal_length'], data['skip_frames_sloth'],
                                                  data['resolution'])

    # Play data through sloth
    for i_frame, record in enumerate(data['data_log']):
        res = record['res']

        res_people = []
        for r in res:
            r['meas_recorded'] = r['meas']
            del r['meas']
            res_people.append(FakePerson(r))

        people_range_estimator.set_distance(res_people, data['distance_scale_factor'])
        print(f'pos = {record['pos_frame']}')
        for rp in res_people:
            d_rec = rp.meas_recorded['dist']
            try:
                d = rp.meas['dist']
            except KeyError:
                d = None
            print(f'{id} : has_pose={rp.has_pose}, d_rec={d_rec}, d={d}')


########################################################################################################################
if __name__ == '__main__':
    main()
